// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: results.proto

package cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto;

public final class ResultsTable {
  private ResultsTable() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MoleculeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 id = 1;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    // optional double x = 2;
    /**
     * <code>optional double x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>optional double x = 2;</code>
     */
    double getX();

    // optional double y = 3;
    /**
     * <code>optional double y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>optional double y = 3;</code>
     */
    double getY();

    // optional double z = 4;
    /**
     * <code>optional double z = 4;</code>
     */
    boolean hasZ();
    /**
     * <code>optional double z = 4;</code>
     */
    double getZ();

    // optional double sigma = 5;
    /**
     * <code>optional double sigma = 5;</code>
     */
    boolean hasSigma();
    /**
     * <code>optional double sigma = 5;</code>
     */
    double getSigma();

    // optional double sigma2 = 6;
    /**
     * <code>optional double sigma2 = 6;</code>
     */
    boolean hasSigma2();
    /**
     * <code>optional double sigma2 = 6;</code>
     */
    double getSigma2();

    // optional double intensity = 7;
    /**
     * <code>optional double intensity = 7;</code>
     */
    boolean hasIntensity();
    /**
     * <code>optional double intensity = 7;</code>
     */
    double getIntensity();

    // optional double background = 8;
    /**
     * <code>optional double background = 8;</code>
     */
    boolean hasBackground();
    /**
     * <code>optional double background = 8;</code>
     */
    double getBackground();
  }
  /**
   * Protobuf type {@code cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule}
   */
  public static final class Molecule extends
      com.google.protobuf.GeneratedMessage
      implements MoleculeOrBuilder {
    // Use Molecule.newBuilder() to construct.
    private Molecule(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Molecule(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Molecule defaultInstance;
    public static Molecule getDefaultInstance() {
      return defaultInstance;
    }

    public Molecule getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Molecule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              x_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              y_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              z_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              sigma_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              sigma2_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              intensity_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              background_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.class, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder.class);
    }

    public static com.google.protobuf.Parser<Molecule> PARSER =
        new com.google.protobuf.AbstractParser<Molecule>() {
      public Molecule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Molecule(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Molecule> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional double x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private double x_;
    /**
     * <code>optional double x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double x = 2;</code>
     */
    public double getX() {
      return x_;
    }

    // optional double y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private double y_;
    /**
     * <code>optional double y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double y = 3;</code>
     */
    public double getY() {
      return y_;
    }

    // optional double z = 4;
    public static final int Z_FIELD_NUMBER = 4;
    private double z_;
    /**
     * <code>optional double z = 4;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double z = 4;</code>
     */
    public double getZ() {
      return z_;
    }

    // optional double sigma = 5;
    public static final int SIGMA_FIELD_NUMBER = 5;
    private double sigma_;
    /**
     * <code>optional double sigma = 5;</code>
     */
    public boolean hasSigma() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double sigma = 5;</code>
     */
    public double getSigma() {
      return sigma_;
    }

    // optional double sigma2 = 6;
    public static final int SIGMA2_FIELD_NUMBER = 6;
    private double sigma2_;
    /**
     * <code>optional double sigma2 = 6;</code>
     */
    public boolean hasSigma2() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double sigma2 = 6;</code>
     */
    public double getSigma2() {
      return sigma2_;
    }

    // optional double intensity = 7;
    public static final int INTENSITY_FIELD_NUMBER = 7;
    private double intensity_;
    /**
     * <code>optional double intensity = 7;</code>
     */
    public boolean hasIntensity() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double intensity = 7;</code>
     */
    public double getIntensity() {
      return intensity_;
    }

    // optional double background = 8;
    public static final int BACKGROUND_FIELD_NUMBER = 8;
    private double background_;
    /**
     * <code>optional double background = 8;</code>
     */
    public boolean hasBackground() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional double background = 8;</code>
     */
    public double getBackground() {
      return background_;
    }

    private void initFields() {
      id_ = 0;
      x_ = 0D;
      y_ = 0D;
      z_ = 0D;
      sigma_ = 0D;
      sigma2_ = 0D;
      intensity_ = 0D;
      background_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, z_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, sigma_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, sigma2_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, intensity_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, background_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, z_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, sigma_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, sigma2_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, intensity_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, background_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.class, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder.class);
      }

      // Construct using cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        sigma_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        sigma2_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        intensity_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        background_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_descriptor;
      }

      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule getDefaultInstanceForType() {
        return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.getDefaultInstance();
      }

      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule build() {
        cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule buildPartial() {
        cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule result = new cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.z_ = z_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sigma_ = sigma_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sigma2_ = sigma2_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.intensity_ = intensity_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.background_ = background_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule) {
          return mergeFrom((cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule other) {
        if (other == cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        if (other.hasSigma()) {
          setSigma(other.getSigma());
        }
        if (other.hasSigma2()) {
          setSigma2(other.getSigma2());
        }
        if (other.hasIntensity()) {
          setIntensity(other.getIntensity());
        }
        if (other.hasBackground()) {
          setBackground(other.getBackground());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 id = 1;
      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional double x = 2;
      private double x_ ;
      /**
       * <code>optional double x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double x = 2;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>optional double x = 2;</code>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0D;
        onChanged();
        return this;
      }

      // optional double y = 3;
      private double y_ ;
      /**
       * <code>optional double y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double y = 3;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>optional double y = 3;</code>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0D;
        onChanged();
        return this;
      }

      // optional double z = 4;
      private double z_ ;
      /**
       * <code>optional double z = 4;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double z = 4;</code>
       */
      public double getZ() {
        return z_;
      }
      /**
       * <code>optional double z = 4;</code>
       */
      public Builder setZ(double value) {
        bitField0_ |= 0x00000008;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double z = 4;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        z_ = 0D;
        onChanged();
        return this;
      }

      // optional double sigma = 5;
      private double sigma_ ;
      /**
       * <code>optional double sigma = 5;</code>
       */
      public boolean hasSigma() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double sigma = 5;</code>
       */
      public double getSigma() {
        return sigma_;
      }
      /**
       * <code>optional double sigma = 5;</code>
       */
      public Builder setSigma(double value) {
        bitField0_ |= 0x00000010;
        sigma_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double sigma = 5;</code>
       */
      public Builder clearSigma() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sigma_ = 0D;
        onChanged();
        return this;
      }

      // optional double sigma2 = 6;
      private double sigma2_ ;
      /**
       * <code>optional double sigma2 = 6;</code>
       */
      public boolean hasSigma2() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double sigma2 = 6;</code>
       */
      public double getSigma2() {
        return sigma2_;
      }
      /**
       * <code>optional double sigma2 = 6;</code>
       */
      public Builder setSigma2(double value) {
        bitField0_ |= 0x00000020;
        sigma2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double sigma2 = 6;</code>
       */
      public Builder clearSigma2() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sigma2_ = 0D;
        onChanged();
        return this;
      }

      // optional double intensity = 7;
      private double intensity_ ;
      /**
       * <code>optional double intensity = 7;</code>
       */
      public boolean hasIntensity() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double intensity = 7;</code>
       */
      public double getIntensity() {
        return intensity_;
      }
      /**
       * <code>optional double intensity = 7;</code>
       */
      public Builder setIntensity(double value) {
        bitField0_ |= 0x00000040;
        intensity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double intensity = 7;</code>
       */
      public Builder clearIntensity() {
        bitField0_ = (bitField0_ & ~0x00000040);
        intensity_ = 0D;
        onChanged();
        return this;
      }

      // optional double background = 8;
      private double background_ ;
      /**
       * <code>optional double background = 8;</code>
       */
      public boolean hasBackground() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional double background = 8;</code>
       */
      public double getBackground() {
        return background_;
      }
      /**
       * <code>optional double background = 8;</code>
       */
      public Builder setBackground(double value) {
        bitField0_ |= 0x00000080;
        background_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double background = 8;</code>
       */
      public Builder clearBackground() {
        bitField0_ = (bitField0_ & ~0x00000080);
        background_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule)
    }

    static {
      defaultInstance = new Molecule(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule)
  }

  public interface ResultsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    java.util.List<cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule> 
        getMoleculeList();
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule getMolecule(int index);
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    int getMoleculeCount();
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    java.util.List<? extends cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder> 
        getMoleculeOrBuilderList();
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder getMoleculeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Results}
   */
  public static final class Results extends
      com.google.protobuf.GeneratedMessage
      implements ResultsOrBuilder {
    // Use Results.newBuilder() to construct.
    private Results(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Results(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Results defaultInstance;
    public static Results getDefaultInstance() {
      return defaultInstance;
    }

    public Results getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Results(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                molecule_ = new java.util.ArrayList<cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule>();
                mutable_bitField0_ |= 0x00000001;
              }
              molecule_.add(input.readMessage(cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          molecule_ = java.util.Collections.unmodifiableList(molecule_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results.class, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results.Builder.class);
    }

    public static com.google.protobuf.Parser<Results> PARSER =
        new com.google.protobuf.AbstractParser<Results>() {
      public Results parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Results(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Results> getParserForType() {
      return PARSER;
    }

    // repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;
    public static final int MOLECULE_FIELD_NUMBER = 1;
    private java.util.List<cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule> molecule_;
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    public java.util.List<cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule> getMoleculeList() {
      return molecule_;
    }
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    public java.util.List<? extends cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder> 
        getMoleculeOrBuilderList() {
      return molecule_;
    }
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    public int getMoleculeCount() {
      return molecule_.size();
    }
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule getMolecule(int index) {
      return molecule_.get(index);
    }
    /**
     * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
     */
    public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder getMoleculeOrBuilder(
        int index) {
      return molecule_.get(index);
    }

    private void initFields() {
      molecule_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < molecule_.size(); i++) {
        output.writeMessage(1, molecule_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < molecule_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, molecule_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Results}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.ResultsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results.class, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results.Builder.class);
      }

      // Construct using cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMoleculeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (moleculeBuilder_ == null) {
          molecule_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          moleculeBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_descriptor;
      }

      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results getDefaultInstanceForType() {
        return cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results.getDefaultInstance();
      }

      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results build() {
        cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results buildPartial() {
        cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results result = new cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results(this);
        int from_bitField0_ = bitField0_;
        if (moleculeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            molecule_ = java.util.Collections.unmodifiableList(molecule_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.molecule_ = molecule_;
        } else {
          result.molecule_ = moleculeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results) {
          return mergeFrom((cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results other) {
        if (other == cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results.getDefaultInstance()) return this;
        if (moleculeBuilder_ == null) {
          if (!other.molecule_.isEmpty()) {
            if (molecule_.isEmpty()) {
              molecule_ = other.molecule_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMoleculeIsMutable();
              molecule_.addAll(other.molecule_);
            }
            onChanged();
          }
        } else {
          if (!other.molecule_.isEmpty()) {
            if (moleculeBuilder_.isEmpty()) {
              moleculeBuilder_.dispose();
              moleculeBuilder_ = null;
              molecule_ = other.molecule_;
              bitField0_ = (bitField0_ & ~0x00000001);
              moleculeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMoleculeFieldBuilder() : null;
            } else {
              moleculeBuilder_.addAllMessages(other.molecule_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Results) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;
      private java.util.List<cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule> molecule_ =
        java.util.Collections.emptyList();
      private void ensureMoleculeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          molecule_ = new java.util.ArrayList<cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule>(molecule_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder> moleculeBuilder_;

      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public java.util.List<cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule> getMoleculeList() {
        if (moleculeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(molecule_);
        } else {
          return moleculeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public int getMoleculeCount() {
        if (moleculeBuilder_ == null) {
          return molecule_.size();
        } else {
          return moleculeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule getMolecule(int index) {
        if (moleculeBuilder_ == null) {
          return molecule_.get(index);
        } else {
          return moleculeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public Builder setMolecule(
          int index, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule value) {
        if (moleculeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMoleculeIsMutable();
          molecule_.set(index, value);
          onChanged();
        } else {
          moleculeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public Builder setMolecule(
          int index, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder builderForValue) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          molecule_.set(index, builderForValue.build());
          onChanged();
        } else {
          moleculeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public Builder addMolecule(cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule value) {
        if (moleculeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMoleculeIsMutable();
          molecule_.add(value);
          onChanged();
        } else {
          moleculeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public Builder addMolecule(
          int index, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule value) {
        if (moleculeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMoleculeIsMutable();
          molecule_.add(index, value);
          onChanged();
        } else {
          moleculeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public Builder addMolecule(
          cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder builderForValue) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          molecule_.add(builderForValue.build());
          onChanged();
        } else {
          moleculeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public Builder addMolecule(
          int index, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder builderForValue) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          molecule_.add(index, builderForValue.build());
          onChanged();
        } else {
          moleculeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public Builder addAllMolecule(
          java.lang.Iterable<? extends cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule> values) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          super.addAll(values, molecule_);
          onChanged();
        } else {
          moleculeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public Builder clearMolecule() {
        if (moleculeBuilder_ == null) {
          molecule_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          moleculeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public Builder removeMolecule(int index) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          molecule_.remove(index);
          onChanged();
        } else {
          moleculeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder getMoleculeBuilder(
          int index) {
        return getMoleculeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder getMoleculeOrBuilder(
          int index) {
        if (moleculeBuilder_ == null) {
          return molecule_.get(index);  } else {
          return moleculeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public java.util.List<? extends cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder> 
           getMoleculeOrBuilderList() {
        if (moleculeBuilder_ != null) {
          return moleculeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(molecule_);
        }
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder addMoleculeBuilder() {
        return getMoleculeFieldBuilder().addBuilder(
            cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.getDefaultInstance());
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder addMoleculeBuilder(
          int index) {
        return getMoleculeFieldBuilder().addBuilder(
            index, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.getDefaultInstance());
      }
      /**
       * <code>repeated .cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Molecule molecule = 1;</code>
       */
      public java.util.List<cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder> 
           getMoleculeBuilderList() {
        return getMoleculeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder> 
          getMoleculeFieldBuilder() {
        if (moleculeBuilder_ == null) {
          moleculeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.Molecule.Builder, cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.ResultsTable.MoleculeOrBuilder>(
                  molecule_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          molecule_ = null;
        }
        return moleculeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Results)
    }

    static {
      defaultInstance = new Results(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cz.cuni.lf1.lge.ThunderSTORM.ImportExport.proto.Results)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rresults.proto\022/cz.cuni.lf1.lge.Thunder" +
      "STORM.ImportExport.proto\"}\n\010Molecule\022\n\n\002" +
      "id\030\001 \001(\r\022\t\n\001x\030\002 \001(\001\022\t\n\001y\030\003 \001(\001\022\t\n\001z\030\004 \001(" +
      "\001\022\r\n\005sigma\030\005 \001(\001\022\016\n\006sigma2\030\006 \001(\001\022\021\n\tinte" +
      "nsity\030\007 \001(\001\022\022\n\nbackground\030\010 \001(\001\"V\n\007Resul" +
      "ts\022K\n\010molecule\030\001 \003(\01329.cz.cuni.lf1.lge.T" +
      "hunderSTORM.ImportExport.proto.MoleculeB" +
      "?\n/cz.cuni.lf1.lge.ThunderSTORM.ImportEx" +
      "port.protoB\014ResultsTable"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Molecule_descriptor,
              new java.lang.String[] { "Id", "X", "Y", "Z", "Sigma", "Sigma2", "Intensity", "Background", });
          internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cz_cuni_lf1_lge_ThunderSTORM_ImportExport_proto_Results_descriptor,
              new java.lang.String[] { "Molecule", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
